config/routes.rb
Rails.application.routes.draw do

  # match '/' => redirect('http://store.kiik.com.br'), via: [:get, :post]
  # match '*path' => redirect('http://store.kiik.com.br'), via: [:get, :post]

  # Root Route
  root to: 'pages#home'

  # Admin
  mount Shoppe::Engine => '/admin'

  # Browse Products
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'

  # Order Status
  get 'order/:token' => 'orders#status', as: 'order_status'

  # Basket
  get 'basket' => 'orders#wizard', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'

  # Checkout
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/refresh' => 'orders#update_order', :as => 'update_order', :via => [:get, :patch]
  match 'checkout/pay' => 'orders#payment', :as => 'payment', :via => [:get, :patch]
  match 'checkout/pay-now-kiik', to: 'orders#pay_now', as: 'pay_now', via: [:get, :patch]

  match 'checkout/billet' => 'orders#billet', :as => 'billet', :via => [:get, :patch]
  match 'checkout/pay-pal' => 'orders#paypal', :as => 'paypal', :via => [:get, :patch]
  match 'checkout/card-information' => 'orders#card_information', :as => 'card_information', :via => [:get, :patch]
  match 'checkout/redirect-pay-pal' => 'orders#redirect_paypal', :as => 'redirect_paypal', :via => [:get, :patch]

  match 'checkout/finalize' => 'orders#finalize', :as => 'finalize', via: :get
  match 'checkout/finish-order/:id' => 'orders#finish_order', :as => 'finish_order', via: :put

end

app/views/shared/_basket.html.haml
.col-md-2.header-basket
	= link_to basket_path, class: "cart-link" do
		- if has_order? && current_order.has_items?
			%p.cart
				%i.fa.fa-shopping-cart.fa-2x
				&nbsp;
				%b.cart-quantity
					%span.badge.label-danger{style: 'background-color: orange'}= current_order.total_items
					= "#{number_to_currency current_order.total_before_tax}"
		- else
			%p.empty
				%i.fa.fa-shopping-cart.fa-2x
				%b.cart-quantity &nbsp;  Vazio

:javascript
	var dispatcher, uri;
	uri = window.document.location.host + "/websocket";
	dispatcher = new WebSocketRails(uri);
	dispatcher.on_open = function(data) {
	  return console.log('Connection has been established');
	};
	dispatcher.bind('order_finished', function(data) {
		amount = (data.amount / 100).toFixed(2)
		if(data.avatar === undefined){
			var avatar = 'https://graph.facebook.com/'+data.facebook_id+'/picture?type=large'
		}else{
			var avatar = data.avatar
		}
		if(window.location.pathname === "/basket"){
			$('#payment_alert').html('<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">'+
			  '<div class="modal-dialog" role="document">'+
			    '<div class="modal-content">'+
			      '<div class="modal-header" style="text-align: center">'+
			        '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+
			        '<h2 class="modal-title" id="myModalLabel">Pagamento Efetuado</h2>'+
			      '</div>'+
			      '<div class="modal-body" style="text-align: center">'+
			        '<img class="circular" src="'+avatar+'"/>'+
							'<h2 style="color: #f48a21">'+data.name+'<h2/>'+
							'<h4>Seu pagamento de <large>R$'+amount+'</large> foi efetuado com sucesso!</h4>'+
			      '</div>'+
			    '</div>'+
			  '</div>'+
			'</div>')
			window.location.href = window.location.pathname + "#finalize"
			$('#myModal').modal('show')
		}else{
			$('#payment_alert').html('<button href="#" type="button" class="close" data-dismiss="alert">&times;</button>'+
			'<h4>Pagamento Efetuado</h4>'+
			'<p>'+data.name+', seu pagamento de R$'+amount+' foi efetuado com sucesso!</p>')
			$('#payment_alert').addClass('alert alert-success alert-block alert-dismissible fade in')
		}
	});

app/views/shared/_flash_messages.haml
- flash.each do |type, message|
  %div{ class: "alert fade in #{bootstrap_class_for(type)}" }
    %button.close{'data-dissmiss' => 'alert'}
    = message

app/views/shared/_order_items.html.haml
%table.table.table-striped{style: 'table-layout: fixed; width: "100%"'}
  %thead
    %tr
      %td Item
      %td Quantidade
      %td Sub-Total
  %tbody
    - for item in order.order_items
      %tr
        %td.product{style: 'width: "33%"'}
          = item.ordered_item.full_name
          - unless defined?(readonly)
            = link_to image_tag("delete.png"), remove_basket_item_path(item), :method => :delete, :class => 'delete ajax btn btn-xs'
        %td.quantity{style: 'width: "33%"'}
          - unless defined?(readonly)
            %form
              %input#numItem{:max => "10", :min => "1", :name => "quantity", :type => "number", :value=> item.quantity, data: {item_id: item.id}}
        %td.money.total{style: 'width: "33%"'}= number_to_currency item.total

app/views/shared/_product_list.html.haml
%ul.products.row
  - for product in products.includes(:default_image, :product_category)
    %li.col-md-6
      .thumbnail
        .col-md-6.product_img
          %img{src: product.default_image ? product.default_image.path : ''}
        .col-md-6.product_text
          .caption
            %h4#name= product.name
            %h6#description= truncate product.short_description, length: 140
            %h4#price
              = number_to_currency product.price
            = link_to "Comprar", buy_product_path(product.product_category.permalink, product.permalink), class: 'btn btn-default', id: 'buy', method: :post

app/views/shared/_reasons.html.haml
%ul.reasons
  %li.support
    %h4 Suporte técnico que funciona
    %p Queremos te ajudar a ter a melhor experiência. Nos ligue ou mande um email.
  %li.quality
    %h4 Qualidade garantida
    %p Garantia de serviço de qualidade para você se concentrar no seu jogo!
  %li.delivery
    %h4 Confirmação rápida
    %p Assim que houver a confirmação de pagamento você já pode aproveitar seus créditos.