config/routes.rb
Rails.application.routes.draw do

  # match '/' => redirect('http://store.kiik.com.br'), via: [:get, :post]
  # match '*path' => redirect('http://store.kiik.com.br'), via: [:get, :post]

  # Root Route
  root to: 'pages#home'

  # Admin
  mount Shoppe::Engine => '/admin'

  # Browse Products
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'

  # Order Status
  get 'order/:token' => 'orders#status', as: 'order_status'

  # Basket
  get 'basket' => 'orders#wizard', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'

  # Checkout
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/refresh' => 'orders#update_order', :as => 'update_order', :via => [:get, :patch]
  match 'checkout/pay' => 'orders#payment', :as => 'payment', :via => [:get, :patch]
  match 'checkout/pay-now-kiik', to: 'orders#pay_now', as: 'pay_now', via: [:get, :patch]

  match 'checkout/billet' => 'orders#billet', :as => 'billet', :via => [:get, :patch]
  match 'checkout/pay-pal' => 'orders#paypal', :as => 'paypal', :via => [:get, :patch]
  match 'checkout/card-information' => 'orders#card_information', :as => 'card_information', :via => [:get, :patch]
  match 'checkout/redirect-pay-pal' => 'orders#redirect_paypal', :as => 'redirect_paypal', :via => [:get, :patch]

  match 'checkout/finalize' => 'orders#finalize', :as => 'finalize', via: :get
  match 'checkout/finish-order/:id' => 'orders#finish_order', :as => 'finish_order', via: :put

end

app/controllers/orders_controller.rb
# coding: utf-8
require 'httparty'
include ActionView::Helpers::NumberHelper

class OrdersController < ApplicationController
  include ActiveMerchant::Billing
  include PaypalExpressHelper
  include WebsocketRails

  before_action :authenticate

  def show
    @hide_header = true
  end

  def wizard
    @hide_header = true
    unless current_order.order_items.any?
      flash[:notice] = 'Carrinho vazio! (:'
      redirect_to root_path
    end
    payment
  end

  def checkout
    @order = current_order
    @hide_header = true
    if request.patch? #&& @order.proceed_to_confirm(order_params)
      redirect_to checkout_payment_path
    end
  end

  def payment
    @code = create_order(current_order)
  end

  def create_order(current_order)
    return if current_order.order_items.empty?
    @code = current_order.kiik_token
    return @code if @code
    items = current_order.order_items.map do |item|
      {
        product_description: item.ordered_item.name,
        price_unit: item.ordered_item.price.to_s,
        quant: item.quantity
      }
    end

    header = {
      Accept: 'application/json'
    }

    auth = {
      username: '8210882a5815600efc6090455e3b1178228cebd7',
      password: ''
    }

    body = {
      order: {
        metadata: {
          callback_url: "http://#{request.headers['HTTP_HOST']}/checkout/finish-order",
          items: items
        },
        amount: items.map { |x| x[:price_unit] }.sum.to_f * 100,
        company_identifier: "010477"
      }
    }


    url = 'http://staging-backend.kiik.com//api/v2/orders'

    response = HTTParty.post(url, header: header, body: body, basic_auth: auth)

    unless response.success?
      flash[:alert] = 'uh oh, houve um erro com a comunicação com o Kiik ):'
      return redirect_to checkout_path
    end
    current_order.update(kiik_token: response["order"]["code"])
    response["order"]["code"]
  end

  def billet
    @order = current_order
  end

  def paypal
    @hide_header = true
  end

  def card_information
    @hide_header = true
    @order = current_order
  end

  def redirect_paypal
    @order = current_order

    items = @order.order_items.map do |item|
      {
        name: item.ordered_item.name,
        description: item.ordered_item.description,
        quantity: item.quantity,
        amount: to_cent(item.ordered_item.price)
      }
    end

    response = EXPRESS_GATEWAY.setup_purchase(to_cent(@order.total),
      items: items,
      ip: request.remote_ip,
      return_url: confirmation_url,
      cancel_return_url: catalogue_url,
      brand_name: 'Kiik::Store',
      cart_border_color: '000CD')
    unless response.success?
      flash[:alert] = 'uh oh, houve um erro com a comunicação com o Paypal ):'
      return redirect_to checkout_path
    end

    redirect_to EXPRESS_GATEWAY.redirect_url_for(response.token)
  end

  def finalize
    @hide_header = false
    reset_session
    current_order = nil

    render partial: 'orders/finalize', layout: false
  end

  def finish_order
    current_order = Shoppe::Order.find_by_kiik_token(params[:id])
    WebsocketRails.users[$redis.get(current_order.id)].send_message :order_finished, params[:order]
    render html: "ok".html_safe
  end

  def remove_item
    current_order_item = Shoppe::OrderItem.find(params[:order_item_id])
    current_order_item.destroy

    return redirect_to basket_path if current_order.order_items.any?
    redirect_to root_path
  end

  def destroy
    @current_order.destroy
    session[:order_id] = nil
    redirect_to root_path, notice: 'Basket Empty (:'
  end

  def change_item_quantity
    order_item_id = params['order_item_id']
    quantity = params['quantity']
    order_item = current_order.order_items.find(order_item_id)
    order_item.quantity = quantity
    order_item.save!

    total = number_to_currency(order_item.order.total, unit: "R$", separator: ",", delimiter: ".")

    render html: "#{total}".html_safe
  end

  def update_order
  end

  def pay_now
    @code = create_order(current_order)
    respond_to do |format|
      format.json { return render(partial: 'orders/pay_now', layout: false, formats: [:html])}
    end
  end

  private

  def order_params
    params[:order].permit(
      :first_name,
      :last_name,
      :billing_address1,
      :billing_address2,
      :billing_address3,
      :billing_address4,
      :billing_country_id,
      :billing_postcode,
      :email_address,
      :phone_number
    )
  end

  def create_payment(order)
    544515
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_billet.haml
- @page_title = 'Emitir Boleto!'

.checkout
  %h2 Preenchimento de Cadastro
  %p.intro Preencha os dados para a emissão do Boleto
  %br
  .customer

    .row
      .col-md-6
        %form
          .form-group
            %label{:for => "InputEmail"} Preencha com seu e-mail:
            %input#InputEmail.form-control{:placeholder => "Email", :type => "email"}/
          .form-group
            %label{:for => "InputPassword"} Senha:
            %input#InputPassword.form-control{:placeholder => "Senha", :type => "password"}/
          .form-group
            %label{:for => "InputConfirmPassword"} Confirme sua Senha:
            %input#InputConfirmPassword.form-control{:placeholder => "Confirmar Senha", :type => "password"}/

          .form-group
            %label{:for => "InputName"} Nome:
            %input#InputName.form-control{:placeholder => "Nome", :type => "text"}/

          .form-group
            %label{:for => "InputCPF"} CPF:
            %input#InputCPF.form-control{:placeholder => "CPF", :type => "password"}/

          .form-group
            %label{:for => "InputBirthDate"} Data de Nascimento (dia/mês/ano):
            %input#InputBirthDate.form-control{:placeholder => "Data de Nascimento", :type => "text"}/

          .form-group
            %label{:for => "InputPhone"} Telefone (xx) xxxx-xxxx:
            %input#InputPhone.form-control{:placeholder => "Telefone", :type => "text"}/
      .col-md-6

        %form
          .form-group
            %label{:for => "InputMobile"} Telefone Celular (xx) x-xxxx-xxxx:
            %input#InputMobile.form-control{:placeholder => "Telefone Celular", :type => "text"}/

          .form-group
            %label{:for => "InputStreet"} Endereço de Cobrança:
            %input#InputStreet.form-control{:placeholder => "Endereço", :type => "text"}/

          .form-group
            %label{:for => "InputNumber"} Número:
            %input#InputNumber.form-control{:placeholder => "Número", :type => "text"}/

          .form-group
            %label{:for => "InputApartment"} Complemento:
            %input#InputApartment.form-control{:placeholder => "Complemento", :type => "text"}/

          .form-group
            %label{:for => "InputCity"} Cidade:
            %input#InputCity.form-control{:placeholder => "Cidade", :type => "text"}/

          .form-group
            %label{:for => "InputCountry"} País:
            %input#InputCountry.form-control{:placeholder => "País", :type => "text"}/

          .form-group
            %label{:for => "InputPostalCode"} CEP:
            %input#InputPostalCode.form-control{:placeholder => "CEP", :type => "text"}/

    .row
      .col-md-12
        .form-group
          %label{:for => "InLineRadioOptions"} Sexo:
          %label.radio-inline
            %input#inlineRadio1{:name => "inlineRadioOptions", :type => "radio", :value => "option1"}/
            Masculino
          %label.radio-inline
            %input#inlineRadio1{:name => "inlineRadioOptions", :type => "radio", :value => "option2"}/
            Feminino

        .checkbox
          %label
            %input{:type => "checkbox", :id => "selectado"}/
            Deseja que a entrega seja feita em outro endereço?


  %dl.delivery{:id => "txtHidden"}
    .form-group
      %label{:for => "InputStreet"} Endereço de Entrega:
      %input#InputStreet.form-control{:placeholder => "Endereço", :type => "text"}/

    .form-group
      %label{:for => "InputNumber"} Número:
      %input#InputNumber.form-control{:placeholder => "Número", :type => "text"}/

    .form-group
      %label{:for => "InputApartment"} Complemento:
      %input#InputApartment.form-control{:placeholder => "Complemento", :type => "text"}/

    .form-group
      %label{:for => "InputCity"} Cidade:
      %input#InputCity.form-control{:placeholder => "Cidade", :type => "text"}/

    .form-group
      %label{:for => "InputCountry"} País:
      %input#InputCountry.form-control{:placeholder => "País", :type => "text"}/

    .form-group
      %label{:for => "InputPostalCode"} CEP:
      %input#InputPostalCode.form-control{:placeholder => "CEP", :type => "text"}/

app/views/orders/_card_information.haml
- @page_title = 'Dados do Cartão'

.checkout

  %h2 Preenchimento dos dados do Cartão
  %p.intro Preencha os dados de seu cartão

.row
  .col-md-6
    %form
      .form-group
        %label{:for => "InputEmail"} Preencha com seu e-mail:
        %input#InputEmail.form-control{:placeholder => "Email", :type => "email"}/
      .form-group
        %label{:for => "InputPassword"} Senha:
        %input#InputPassword.form-control{:placeholder => "Senha", :type => "password"}/
      .form-group
        %label{:for => "InputConfirmPassword"} Confirme sua Senha:
        %input#InputConfirmPassword.form-control{:placeholder => "Confirmar Senha", :type => "password"}/

      .form-group
        %label{:for => "InputName"} Nome:
        %input#InputName.form-control{:placeholder => "Nome", :type => "text"}/

      .form-group
        %label{:for => "InputCPF"} CPF:
        %input#InputCPF.form-control{:placeholder => "CPF", :type => "password"}/

      .form-group
        %label{:for => "InputBirthDate"} Data de Nascimento (dia/mês/ano):
        %input#InputBirthDate.form-control{:placeholder => "Data de Nascimento", :type => "text"}/

      .form-group
        %label{:for => "InputPhone"} Telefone (xx) xxxx-xxxx:
        %input#InputPhone.form-control{:placeholder => "Telefone", :type => "text"}/

  .col-md-6
    %form
      .form-group
        %label{:for => "InputMobile"} Telefone Celular (xx) x-xxxx-xxxx:
        %input#InputMobile.form-control{:placeholder => "Telefone Celular", :type => "text"}/

      .form-group
        %label{:for => "InputStreet"} Endereço de Cobrança:
        %input#InputStreet.form-control{:placeholder => "Endereço", :type => "text"}/

      .form-group
        %label{:for => "InputNumber"} Número:
        %input#InputNumber.form-control{:placeholder => "Número", :type => "text"}/

      .form-group
        %label{:for => "InputApartment"} Complemento:
        %input#InputApartment.form-control{:placeholder => "Complemento", :type => "text"}/

      .form-group
        %label{:for => "InputCity"} Cidade:
        %input#InputCity.form-control{:placeholder => "Cidade", :type => "text"}/

      .form-group
        %label{:for => "InputCountry"} País:
        %input#InputCountry.form-control{:placeholder => "País", :type => "text"}/

        .form-group
        %label{:for => "InputPostalCode"} CEP:
        %input#InputPostalCode.form-control{:placeholder => "CEP", :type => "text"}/

.row
  .col-md-12
    %hr
    %form
      .form-group
        %label{:for => "InputCardNumber"} Número do Cartão:
        %input#InputCardNumber.form-control{:placeholder => "Número do Cartão", :type => "text"}/

      .form-group
        %label{:for => "InputName"} Nome impresso no Cartão:
        %input#InputName.form-control{:placeholder => "Nome", :type => "text"}/

      .form-group
        %label{:for => "InputDate"} Validade (mês/ano):
        %input#InputDate.form-control{:placeholder => "Validade", :type => "password"}/

      .form-group
        %label{:for => "InputPassCode"} Insira o Código de Segurança:
        %input#InputPassCode.form-control{:placeholder => "Código de Segurança", :type => "password"}/

app/views/orders/_checkout.html.haml
ew- @page_title = 'Checkout'

%table.table.table-striped{style: 'table-layout: fixed; width: "100%";'}
  %thead
    %tr
      %td{:align => "center"} KIIK
      %td{:align => "center"} CARTÃO DE CRÉDITO
      %td{:align => "center"} PAYPAL
      %td{:align => "center"} BOLETO BANCÁRIO
  %tbody
    %tr
      %td{:align => "center"}
        = image_tag("kiik-payment.png")
      %td{:align => "center"}
        = image_tag("credit-card.png")
      %td{:align => "center"}
        = image_tag("pay-pal-payment.png")
      %td{:align => "center"}
        = image_tag("billet-payment.png")
    %tr#button_group
      %input#button_value{:name => "button_value", :type => "hidden", :value => ""}/
      %td
        %span.radiobuttons
          %button#button1_button_off.redradio{:name => "button1_button_off", :onclick => "switchON('button_group','button_value','button1',this.value); select_kiik()", :type => "button", :value => "OFF1"}
          %button#button1_button_on.greenradio{:name => "button1_button_on", :style => "display:none;", :type => "button", :value => "ON1"}
      %td
        %span.radiobuttons
          %button#button2_button_off.redradio{:name => "button2_button_off", :onclick => "switchON('button_group','button_value','button2',this.value); select_cards()", :type => "button", :value => "OFF2"}
          %button#button2_button_on.greenradio{:name => "button2_button_on", :style => "display:none;", :type => "button", :value => "ON2"}
      %td
        %span.radiobuttons
          %button#button3_button_off.redradio{:name => "button3_button_off", :onclick => "switchON('button_group','button_value','button3',this.value); select_paypal()", :type => "button", :value => "OFF3"}
          %button#button3_button_on.greenradio{:name => "button3_button_on", :style => "display:none;", :type => "button", :value => "ON3"}
      %td
        %span.radiobuttons
          %button#button4_button_off.redradio{:name => "button4_button_off", :onclick => "switchON('button_group','button_value','button4',this.value); select_billet()", :type => "button", :value => "OFF4"}
          %button#button4_button_on.greenradio{:name => "button4_button_on", :style => "display:none;", :type => "button", :value => "ON4"} 

    <!-- %tr -->
    <!--   - for item in current_order.order_items -->
    <!--     %tr -->
    <!--       %td.product -->
    <!--         = item.ordered_item.full_name -->
    <!--       %td.quantity -->
    <!--         %label item.quantity -->
    <!--       %td.money.total -->
    <!--         = number_to_currency item.total -->

app/views/orders/_checkout_sidebar.html.haml
= content_for :sidebar do
  .checkout
    %dl
      %dt Quais pagamentos são aceitos?
      

app/views/orders/_finalize.haml
- @page_title = 'KiiK::Store'

.row
  .col-md-6
    = image_tag 'kiik.png', height: '100px', class: 'center-block'
  .col-md-6
    %p.lead{style: 'margin-top: 40px'} Obrigado por testar o Kiik!

%hr

%a.btn.btn-block.btn-primary{ href: 'https://secure.kiik.com.br/', target: '_blank' } 
  = fa_icon 'apple'
  Baixe o Kiik aqui!
  = fa_icon 'android'

app/views/orders/_pay_now.haml
.modal.fade.in#pay_now_modal{tabindex: '-1', role: 'dialog', 'aria-labelledby' => 'pay_now_modal_label'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{type: 'button', 'data-dismiss' => 'modal', 'aria-label' => 'Close'}
          %span{'aria-hidden' => true}x
        %h2.modal-title#pay_now_modal_label{style: 'text-align:center'} Pague agora com o KiiK
      .modal-body
        - if @code
          - @qrcode = RQRCode::QRCode.new(@code)
          .row.margin-qrcode
            .col-md-4.col-md-offset-4
              %table{style: "margin:auto"}
                - @qrcode.modules.each_index do |x|
                  %tr
                    - @qrcode.modules.each_index do |y|
                      - if @qrcode.dark?(x,y)
                        %td.black
                      - else
                        %td.white
              %br
              %p.lead.text-center
                = @code
              %p.lead.text-center
                = link_to("Abrir app do KiiK", "kiik://qrcode/#{@code}", class: 'btn btn-warning')
        - else
          %p.lead.text-center Adicione itens ao seu carrinho antes de fazer o pagamento!

app/views/orders/_payment.haml
- require 'rqrcode'
- @page_title = 'Pagar com Kiik'
%input{type: 'hidden', value: @code, id: 'qr_code'}
- @qrcode = RQRCode::QRCode.new(@code)
.row.margin-qrcode
  .col-md-4.col-md-offset-4
    %table{style: "margin:auto"}
      - @qrcode.modules.each_index do |x|
        %tr
          - @qrcode.modules.each_index do |y|
            - if @qrcode.dark?(x,y)
              %td.black
            - else
              %td.white
    %br
    %p.lead.text-center
      = @code
    %p.lead.text-center
      = link_to("Abrir app do KiiK", "kiik://qrcode/#{@code}", class: 'btn btn-warning')

    %p Parabéns por escolher o KiiK. Abra o aplicativo para ler o QR Code e concluir o pagamento de uma forma rápida e segura.
  .col-md-7
    #details
%br
%hr.dash

app/views/orders/_paypal.haml
- @page_title = 'KiiK::Store'

.checkout
  %h2 Você será redirecionado para o Pagamento
  %p.intro Clique na imagem abaixo para ser redirecionado ao pagamento
  %br

  .row
    .col-md-12
      = link_to(image_tag('https://www.paypalobjects.com/webstatic/en_US/i/buttons/buy-logo-large.png'), redirect_paypal_path, target: '_blank')

app/views/orders/_show.html.haml
- @page_title = 'Your Shopping Bag'
.checkout
  = render 'shared/order_items', :order => current_order

%hr.dash
.col-md-offset-4
  %a.btn.btn-default.btn-primary{href: '#payment-types'} ESCOLHER FORMA DE PAGAMENTO

app/views/orders/update_order.html.haml
.panel.panel-default
  .panel-body
    .order
      .header{style: 'text-align:center'}
        %h3{style: 'color:#3a87ad'}= "Total do Pedido: #{number_to_currency(@order.order_total)}"
        %h3{style: 'color:#3a87ad'}= "Total Pago: #{number_to_currency(@order.paid_total)}"
      %br
      %hr
      - @order.items.each do |item|
        .row
          .col-md-5
            .circular
              = image_tag("https://graph.facebook.com/#{item['client']['id_facebook']}/picture?type=large")
          .col-md-7
            .username.margin-status
              %p{style: 'font-size: 25px'}= item['client']['name']
            .item_paid.margin-status
              %p{style: 'font-size: 15px'}= "Produto: #{item['client']['items_paid']['normal'][0]['product_description']}"
            .value_paid.margin-status
              %p{style: 'font-size: 15px'}= "Pago: #{number_to_currency(item['client']['paid_value'])}"
        %hr
      - if @order.paid_total.to_f > 0.0 && @order.paid_total.to_f >= @order.order_total.to_f
        = render 'orders/finalize', layout:false

app/views/orders/wizard.haml
- @page_title = 'KiiK::Store'

.checkout
  %br

  #myWizard.wizard{"data-initialize" => "wizard"}
    %ul.steps
      %li.active{"data-name" => "basket", id: "data-step-1"}
        %span.badge> 1
        Meu Carrinho
        %span.chevron
      %li{"data-name"=> "payment-type", id: "data-step-2"}
        %span.badge> 2
        Forma de Pagamento
        %span.chevron
      %li{"data-name" => "payment", id: "data-step-3"}
        %span.badge> 3
        Confirmação
        %span.chevron

    .step-content
      .step-pane.active.sample-pane.alert{"data-step" => "1", id: 'basket'}
        = render 'orders/show', layout: false
      .step-pane.active.sample-pane.alert{"data-step" => "2", id: 'payment-type'}
        = render 'orders/checkout', layout: false
      .step-pane.active.sample-pane.alert{"data-step" => "2", id: 'kiik'}
        = render 'orders/payment', layout: false
      .step-pane.active.sample-pane.alert{"data-step" => "2", id: 'billet'}
        = render 'orders/billet', layout: false
      .step-pane.active.sample-pane.alert{"data-step" => "2", id: 'card'}
        = render 'orders/card_information', layout: false
      .step-pane.active.sample-pane.alert{"data-step" => "2", id: 'paypal'}
        = render 'orders/paypal', layout: false
      .step-pane.active.sample-pane.alert{"data-step" => "3", id: 'finalize'}
        -#= render 'orders/finalize', layout: false