config/routes.rb
Rails.application.routes.draw do

  # match '/' => redirect('http://store.kiik.com.br'), via: [:get, :post]
  # match '*path' => redirect('http://store.kiik.com.br'), via: [:get, :post]

  # Root Route
  root to: 'pages#home'

  # Admin
  mount Shoppe::Engine => '/admin'

  # Browse Products
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'

  # Order Status
  get 'order/:token' => 'orders#status', as: 'order_status'

  # Basket
  get 'basket' => 'orders#wizard', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'

  # Checkout
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/refresh' => 'orders#update_order', :as => 'update_order', :via => [:get, :patch]
  match 'checkout/pay' => 'orders#payment', :as => 'payment', :via => [:get, :patch]
  match 'checkout/pay-now-kiik', to: 'orders#pay_now', as: 'pay_now', via: [:get, :patch]

  match 'checkout/billet' => 'orders#billet', :as => 'billet', :via => [:get, :patch]
  match 'checkout/pay-pal' => 'orders#paypal', :as => 'paypal', :via => [:get, :patch]
  match 'checkout/card-information' => 'orders#card_information', :as => 'card_information', :via => [:get, :patch]
  match 'checkout/redirect-pay-pal' => 'orders#redirect_paypal', :as => 'redirect_paypal', :via => [:get, :patch]

  match 'checkout/finalize' => 'orders#finalize', :as => 'finalize', via: :get
  match 'checkout/finish-order/:id' => 'orders#finish_order', :as => 'finish_order', via: :put

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter do
    if params[:category_id]
      @product_category = Shoppe::ProductCategory.where(:permalink => params[:category_id]).first!
    end
    if @product_category && params[:product_id]
      @product = @product_category.products.where(:permalink => params[:product_id]).active.first!
    end
  end

  def index
    @products = @product_category.products.includes(:default_image, :product_category, :variants).root.active
  end

  def filter
    @products = Shoppe::Product.active.with_attributes(params[:key].to_s, params[:value].to_s)
  end

  def categories
    @product_categories = Shoppe::ProductCategory.ordered.includes(:image)
  end

  def show
    @attributes = @product.product_attributes.public.to_a
  end

  def add_to_basket
    product_to_order = params[:variant] ? @product.variants.find(params[:variant].to_i) : @product
    current_order.order_items.add_item(product_to_order, params[:quantity].blank? ? 1 : params[:quantity].to_i)
    respond_to do |wants|
      wants.html { redirect_to request.referer }
      wants.json { render :json => {:added => true} }
    end
  rescue Shoppe::Errors::NotEnoughStock => e
    respond_to do |wants|
      wants.html { redirect_to request.referer, :alert => "We're sorry but we don't have enough stock to add that many products. We currently have #{e.available_stock} item(s) in stock. Please try again."}
      wants.json { render :json => {:error => 'NotEnoughStock', :available_stock => e.available_stock}}
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/categories.html.haml
- active_nav_item :catalogue
- @page_title = 'Catalogue'
  %ul
    - for category in @product_categories
      %li
        %div.img{:style => category.image ? "background-image:url(#{category.image.path})" : 'background-color:#efefef'}
        .space
          %h4= link_to category.name, products_path(category.permalink)
          %p= category.description

app/views/products/filter.html.haml
- active_nav_item :catalogue
- @page_title = "#{params[:value]} - Products"
.category
  %h2 Products
  %p.intro Displaying products where <b>#{params[:key]}</b> is <b>#{params[:value]}</b>.
  - if @products.empty?
    %p.noProducts There are no products matching your filter
  - else
    = render 'shared/product_list', :products => @products

app/views/products/index.html.haml
- active_nav_item :catalogue
- @page_title = @product_category.name
.category
  = render 'shared/product_list', :products => @products

app/views/products/show.html.haml
/ - active_nav_item :catalogue
- @page_title = @product.name + " - " + @product.product_category.name
.product
  - if @product.default_image
    .img{:style => "background-image:url(#{@product.default_image.path})"}
  %h2= @product.name
  %p.intro= @product.short_description

  - if @product.has_variants?
    %table.variants
      - for variant in @product.variants
        %tr
          %td
            - if variant.in_stock?
              %p.stock.yes In stock
            - else
              %p.stock.no Out of stock
            %h4= variant.name
            %p.price= number_to_currency variant.price
          %td.buy
            = form_tag buy_product_path(@product.product_category.permalink, @product.permalink, :variant => variant.id), :class => (variant.in_stock? ? 'in-stock' : 'no-stock') do
              %p
                = select_tag 'quantity', options_for_select([1,2,3,4,5,6,7,8,9]), :disabled => !variant.in_stock?
                = submit_tag 'Add to basket', :disabled => !variant.in_stock?
  - else
    .optionsBox
      .top
        %p.price= number_to_currency @product.price
        = form_tag buy_product_path(@product.product_category.permalink, @product.permalink), :class => (@product.in_stock? ? 'in-stock' : 'no-stock') do
          %p
            = select_tag 'quantity', options_for_select([1,2,3,4,5,6,7,8,9]), :disabled => !@product.in_stock?
            = submit_tag 'Add to basket', :disabled => !@product.in_stock?
      .bottom
        .stock
          - if @product.in_stock?
            %p.yes Em estoque
          - else
            %p.no Indisponível no estoque
            %p.time Ops - Atualmente não temos nenhum produto em estoque. #{link_to "Me avise quando tiver"}.
        .links
          %ul
            - if @product.data_sheet
              %li.item.datasheet= link_to "Read product datasheet", @product.data_sheet.path
            - unless @product.in_the_box.blank?
              %li.item.box
                = link_to "O que vem ?"
                %div.in_the_box
                  %h3 O que vem dentro?
                  = markdown @product.in_the_box
            %li.item.ask= mail_to Shoppe.settings.email_address, "Faça uma pergunta sobre isto", :subject => "Dúvidas sobre #{@product.name}"

    %hr

  - unless @attributes.empty?
    %table.attributes
      - for attribute in @attributes
        %tr
          %th= attribute.key
          %td= link_to attribute.value, product_filter_path(:key => attribute.key, :value => attribute.value)
  .description
    = markdown @product.description